#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : clr-pyversion-strip
Version  : 1
Release  : 3
URL      : http://localhost/cgit/projects/clr-pyversion-strip/snapshot/clr-pyversion-strip-1.tar.gz
Source0  : http://localhost/cgit/projects/clr-pyversion-strip/snapshot/clr-pyversion-strip-1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
Requires: clr-pyversion-strip-bin = %{version}-%{release}

%description
No detailed description available

%package bin
Summary: bin components for the clr-pyversion-strip package.
Group: Binaries

%description bin
bin components for the clr-pyversion-strip package.


%prep
%setup -q -n clr-pyversion-strip-1
cd %{_builddir}/clr-pyversion-strip-1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1604084315
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%autogen --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1604084315
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/clr-pyversion-strip
